# Configuration Environnement - Application Compagnon Virtuel
# IMPORTANT: Copier ce fichier vers .env et modifier TOUS les mots de passe!

# === ENVIRONNEMENT ===
ENVIRONMENT=development
DEBUG_MODE=true
LOG_LEVEL=INFO

# === BASE DE DONNÉES POSTGRESQL ===
DB_HOST=localhost
DB_PORT=5432
DB_NAME=virtual_companion_db
DB_USERNAME=vc_admin
DB_PASSWORD=CHANGEME_db_secure_password_2024
DB_SSL_MODE=disable
DB_MAX_CONNECTIONS=100
DB_CONNECTION_TIMEOUT=30

# === REDIS CACHE ===
REDIS_HOST=localhost
REDIS_PORT=6379
REDIS_PASSWORD=CHANGEME_redis_secure_password_2024
REDIS_MAX_CONNECTIONS=50
REDIS_CONNECTION_TIMEOUT=5000
REDIS_COMMAND_TIMEOUT=5000

# === ELASTICSEARCH ===
ELASTIC_HOST=localhost
ELASTIC_PORT=9200
ELASTIC_USERNAME=elastic
ELASTIC_PASSWORD=CHANGEME_elastic_secure_password_2024
ELASTIC_INDEX_PREFIX=vc_

# === KAFKA MESSAGING ===
KAFKA_BOOTSTRAP_SERVERS=localhost:9092
KAFKA_CONSUMER_GROUP_ID=virtual-companion-group
KAFKA_AUTO_OFFSET_RESET=latest
KAFKA_ENABLE_AUTO_COMMIT=true
KAFKA_SESSION_TIMEOUT_MS=30000

# === MINIO STORAGE ===
MINIO_ENDPOINT=http://localhost:9000
MINIO_ACCESS_KEY=CHANGEME_minio_access_key
MINIO_SECRET_KEY=CHANGEME_minio_secret_key
MINIO_SECURE=false
MINIO_REGION=us-east-1

# === SECURITÉ & JWT ===
JWT_SECRET=CHANGEME_very_long_and_secure_jwt_secret_key_minimum_512_bits
JWT_EXPIRATION_HOURS=24
JWT_REFRESH_EXPIRATION_DAYS=30
ENCRYPTION_KEY=CHANGEME_32_character_encryption_key_here
BCRYPT_ROUNDS=12

# === API GATEWAY ===
GATEWAY_HOST=0.0.0.0
GATEWAY_PORT=8080
GATEWAY_CORS_ALLOWED_ORIGINS=http://localhost:3000,http://localhost:3001
GATEWAY_RATE_LIMIT_PER_MINUTE=100
GATEWAY_REQUEST_TIMEOUT_SECONDS=30

# === SERVICES PORTS ===
USER_SERVICE_PORT=8081
CHARACTER_SERVICE_PORT=8082
CONVERSATION_SERVICE_PORT=8083
MEDIA_SERVICE_PORT=8084
BILLING_SERVICE_PORT=8085
MODERATION_SERVICE_PORT=8086

# === SERVICES EXTERNES ===
# Stripe (Paiements)
STRIPE_API_KEY=sk_test_CHANGEME
STRIPE_WEBHOOK_SECRET=whsec_CHANGEME
STRIPE_PUBLISHABLE_KEY=pk_test_CHANGEME

# Email (Dev: Mailhog)
SMTP_HOST=localhost
SMTP_PORT=1025
SMTP_USERNAME=
SMTP_PASSWORD=
SMTP_FROM_EMAIL=noreply@virtualcompanion.app
SMTP_FROM_NAME=Virtual Companion
SMTP_TLS_ENABLED=false

# SMS (Twilio - Optionnel)
TWILIO_ACCOUNT_SID=CHANGEME_if_using_sms
TWILIO_AUTH_TOKEN=CHANGEME_if_using_sms
TWILIO_PHONE_NUMBER=+1234567890

# === MODERATION & IA ===
# OpenAI API (pour modération de contenu)
OPENAI_API_KEY=sk-CHANGEME_if_using_openai
OPENAI_MODERATION_MODEL=text-moderation-latest

# Modèle IA Local
LOCAL_AI_MODEL_PATH=/models/llama2-7b
LOCAL_AI_MAX_TOKENS=2048
LOCAL_AI_TEMPERATURE=0.7

# === MONITORING ===
GRAFANA_USER=admin
GRAFANA_PASSWORD=CHANGEME_grafana_password
PROMETHEUS_RETENTION_DAYS=30
METRICS_ENABLED=true
TRACING_ENABLED=true

# === LIMITES & QUOTAS ===
# Utilisateurs gratuits
FREE_DAILY_MESSAGE_LIMIT=10
FREE_CHARACTER_LIMIT=1
FREE_HISTORY_DAYS=7

# Utilisateurs Standard
STANDARD_DAILY_MESSAGE_LIMIT=500
STANDARD_CHARACTER_LIMIT=3
STANDARD_HISTORY_DAYS=30

# Utilisateurs Premium
PREMIUM_DAILY_MESSAGE_LIMIT=unlimited
PREMIUM_CHARACTER_LIMIT=unlimited
PREMIUM_HISTORY_DAYS=unlimited

# === MEDIA & STREAMING ===
MAX_UPLOAD_SIZE_MB=50
ALLOWED_IMAGE_FORMATS=jpg,jpeg,png,webp
ALLOWED_VIDEO_FORMATS=mp4,webm
VIDEO_STREAMING_BITRATE=2000000
AUDIO_STREAMING_BITRATE=128000
WEBRTC_STUN_SERVERS=stun:stun.l.google.com:19302

# === CONFORMITÉ LÉGALE ===
AGE_VERIFICATION_REQUIRED=true
MINIMUM_AGE=18
GDPR_COMPLIANCE_ENABLED=true
CCPA_COMPLIANCE_ENABLED=true
DATA_RETENTION_DAYS=365
CONTENT_MODERATION_STRICT=true

# === GÉOLOCALISATION ===
GEOIP_DATABASE_PATH=/data/GeoLite2-City.mmdb
BLOCKED_COUNTRIES=
ALLOWED_COUNTRIES=

# === DÉVELOPPEMENT ===
# Seeds & Tests
SEED_TEST_USERS=true
SEED_TEST_CHARACTERS=true
TEST_USER_EMAIL=test@example.com
TEST_USER_PASSWORD=TestPassword123!

# Debugging
ENABLE_SQL_LOGGING=true
ENABLE_REQUEST_LOGGING=true
ENABLE_PERFORMANCE_MONITORING=true

# === BACKUP ===
BACKUP_ENABLED=true
BACKUP_SCHEDULE=0 2 * * *
BACKUP_RETENTION_DAYS=30
BACKUP_S3_BUCKET=vc-backups

# === FEATURE FLAGS ===
FEATURE_VIDEO_CHAT_ENABLED=false
FEATURE_VOICE_CHAT_ENABLED=true
FEATURE_MARKETPLACE_ENABLED=false
FEATURE_SOCIAL_SHARING_ENABLED=false
FEATURE_AI_EMOTIONS_ENABLED=true

# === REDIS COMMANDER ===
REDIS_COMMANDER_PASSWORD=CHANGEME_redis_commander_password

# === ADMIN TOOLS ===
ADMIN_EMAIL=admin@virtualcompanion.app
ADMIN_DEFAULT_PASSWORD=CHANGEME_admin_password
ENABLE_ADMIN_PANEL=true
ADMIN_PANEL_PORT=8090