// =============================================================================
// File: src/navigation/TabNavigator.tsx
// Generated by TypeScriptFileParser
// Date: Thu Jun 19 20:53:16 CEST 2025
// =============================================================================

import React from 'react';
import { createBottomTabNavigator } from '@react-navigation/bottom-tabs';
import { Ionicons } from '@expo/vector-icons';
import { BlurView } from 'expo-blur';
import { Platform, View } from 'react-native';
import Animated, {
  useAnimatedStyle,
  withSpring,
  interpolate,
} from 'react-native-reanimated';

import { HomeScreen } from '@/screens/HomeScreen';
import { CharactersScreen } from '@/screens/CharactersScreen';
import { ConversationsScreen } from '@/screens/ConversationsScreen';
import { ProfileScreen } from '@/screens/ProfileScreen';
import { useTheme } from '@/hooks/useTheme';

const Tab = createBottomTabNavigator();

const AnimatedIcon = ({ name, focused, color }: any) => {
  const animatedStyle = useAnimatedStyle(() => ({
    transform: [
      {
        scale: withSpring(focused ? 1.2 : 1, {
          damping: 15,
        }),
      },
    ],
  }));

  return (
    <Animated.View style={animatedStyle}>
      <Ionicons name={name} size={24} color={color} />
    </Animated.View>
  );
};

export function TabNavigator() {
  const { theme } = useTheme();

  return (
    <Tab.Navigator
      screenOptions={{
        headerShown: false,
        tabBarStyle: {
          position: 'absolute',
          backgroundColor: Platform.OS === 'ios' ? 'transparent' : theme.colors.card,
          borderTopWidth: 0,
          elevation: 0,
        },
        tabBarBackground: () =>
          Platform.OS === 'ios' ? (
            <BlurView
              tint={theme.dark ? 'dark' : 'light'}
              intensity={80}
              style={{
                position: 'absolute',
                top: 0,
                left: 0,
                right: 0,
                bottom: 0,
              }}
            />
          ) : null,
        tabBarActiveTintColor: theme.colors.primary,
        tabBarInactiveTintColor: theme.colors.textSecondary,
      }}
    >
      <Tab.Screen
        name="Home"
        component={HomeScreen}
        options={{
          tabBarIcon: ({ focused, color }) => (
            <AnimatedIcon name="home" focused={focused} color={color} />
          ),
        }}
      />
      <Tab.Screen
        name="Characters"
        component={CharactersScreen}
        options={{
          tabBarIcon: ({ focused, color }) => (
            <AnimatedIcon name="people" focused={focused} color={color} />
          ),
        }}
      />
      <Tab.Screen
        name="Chats"
        component={ConversationsScreen}
        options={{
          tabBarIcon: ({ focused, color }) => (
            <AnimatedIcon name="chatbubbles" focused={focused} color={color} />
          ),
        }}
      />
      <Tab.Screen
        name="Profile"
        component={ProfileScreen}
        options={{
          tabBarIcon: ({ focused, color }) => (
            <AnimatedIcon name="person" focused={focused} color={color} />
          ),
        }}
      />
    </Tab.Navigator>
  );
}