# Moderation Service - Configuration

spring:
  application:
    n: moderation-service
  
  profiles:
    active: ${ENVIRONMENT:development}
  
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:virtual_companion_db}?currentSchema=moderation_service
    username: ${DB_USERNAME:vc_admin}
    password: ${DB_PASSWORD:vc_secure_pass_2024}
  
  jpa:
    hibernate:
      ddl-auto: validate
  
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: moderation-service-group
  
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:redis_secure_pass_2024}
  
  flyway:
    enabled: true
    schemas: moderation_service

server:
  port: ${MODERATION_SERVICE_PORT:8086}

# Moderation Configuration
moderation:
  # AI Providers
  providers:
    openai:
      enabled: ${OPENAI_MODERATION_ENABLED:true}
      api-key: ${OPENAI_API_KEY:}
      model: text-moderation-latest
      timeout: 5s

    google:
      enabled: ${GOOGLE_VISION_ENABLED:false}
      credentials-path: ${GOOGLE_CREDENTIALS_PATH:}

    aws:
      enabled: ${AWS_REKOGNITION_ENABLED:false}
      region: ${AWS_REGION:eu-west-1}
      access-key: ${AWS_ACCESS_KEY:}
      secret-key: ${AWS_SECRET_KEY:}

    local:
      enabled: true
      model-path: ${LOCAL_MODEL_PATH:/models/content-moderation}

  # Thresholds
  thresholds:
    # Text moderation
    toxicity: 0.7
    severe-toxicity: 0.8
    threat: 0.8
    insult: 0.7
    profanity: 0.7
    sexual: 0.8
    
    # Image moderation
    nudity: 0.8
    violence: 0.7
    gore: 0.9
    hate-symbols: 0.9
    
    # General
    minimum-confidence: 0.6
    human-review-threshold: 0.5

  # Categories
  categories:
    high-risk:
      - child-safety
      - self-harm
      - violence
      - illegal-content
    medium-risk:
      - sexual-content
      - hate-speech
      - harassment
    low-risk:
      - profanity
      - spam

  # Rules
  rules:
    # Keyword blocking
    blocked-keywords-file: /config/blocked-keywords.txt
    
    # Pattern matching
    suspicious-patterns:
      - "\\b\\d{3}-\\d{2}-\\d{4}\\b"  # SSN pattern
      - "\\b4\\d{3}[\\s-]?\\d{4}[\\s-]?\\d{4}[\\s-]?\\d{4}\\b"  # Credit card

    # Auto-actions
    auto-actions:
      child-safety: IMMEDIATE_BLOCK_AND_REPORT
      self-harm: BLOCK_AND_SUPPORT_MESSAGE
      spam: SHADOW_BAN

  # Age Verification
  age-verification:
    minimum-age: ${MINIMUM_AGE:18}
    methods:
      - DOCUMENT_UPLOAD
      - FACIAL_AGE_ESTIMATION
      - CREDIT_CARD_VERIFICATION
    document-types:
      - PASSPORT
      - DRIVING_LICENSE
      - NATIONAL_ID
    verification-providers:
      - ONFIDO
      - JUMIO
      - LOCAL_AI

  # Queue Processing
  processing:
    thread-pool-size: ${MODERATION_THREADS:10}
    queue-capacity: 1000
    priority-queue: true
    batch-size: 50

  # Human Review
  human-review:
    enabled: true
    queue-threshold: 100
    sla-hours: 24
    escalation-enabled: true

# Cache Configuration
cache:
  user-risk-scores:
    ttl: 1h
    max-size: 10000
  moderation-results:
    ttl: 24h
    max-size: 50000
  blocked-content-hashes:
    ttl: 7d
    max-size: 100000

# Monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

# Kafka Topics
kafka:
  topics:
    moderation-requests: moderation-requests
    moderation-results: moderation-results
    user-warnings: user-warnings
    content-blocked: content-blocked