# kubernetes/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: virtual-companion
type: Opaque
data:
  # Base64 encoded values
  DATABASE_PASSWORD: cG9zdGdyZXNfcGFzc3dvcmQ=
  JWT_SECRET: and0X3NlY3JldF9rZXlfMTIzNDU2Nzg5MA==
  STRIPE_API_KEY: c2tfbGl2ZV9YWFhYWFhYWFhYWFhYWFhYWA==
  STRIPE_WEBHOOK_SECRET: d2hzZWNfWFhYWFhYWFhYWFhYWFhYWFhY
  AWS_ACCESS_KEY_ID: QUtJQVhYWFhYWFhYWFhYWFhY
  AWS_SECRET_ACCESS_KEY: YXdzX3NlY3JldF9rZXlfWFhYWFhYWFhY
  OPENAI_API_KEY: c2stWFhYWFhYWFhYWFhYWFhYWFhYWFhY